default: &default
  adapter: postgresql
  encoding: unicode
  # Para detalhes sobre pooling de conexões, veja o guia de configuração do Rails
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Essas variáveis individuais são usadas se DATABASE_URL não estiver definida.
  # Para desenvolvimento local com docker-compose, elas são úteis.
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>

development:
  <<: *default
  database: task_manager_development

test:
  <<: *default
  database: task_manager_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  cable:
    url: <%= ENV["DATABASE_URL"] %>
    adapter: postgresql
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
