service: task_manager

image: task_manager/task_manager
servers:
  - 144.22.150.53

logging:
  driver: local
  options:
    max-size: "10m"
    max-file: "3"
registry:
  server: 144.22.150.53:5000
  username: 
    - REGISTRY_USERNAME
  password: 
    - REGISTRY_PASSWORD

builder:
  arch: amd64
  local: true

env:
  secret:
    - DATABASE_USERNAME
    - DATABASE_PASSWORD
    - DATABASE_HOST
    - DATABASE_PORT
    - RAILS_MASTER_KEY

volumes:
  - "/app/config/master.key:/config/master.key:ro"
  - "/app/config/credentials.yml.enc:/config/credentials.yml.enc:ro"
  - "/app/log:/app/log"

proxy:
  ssl: false
  ssl_redirect: false
  app_port: 80
  forward_headers: false

ssh:
  user: ubuntu

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails db:console"

accessories:
  db:
    image: postgres:16
    host: 144.22.150.53
    port: 5432
    env:
      secret:
        - DATABASE_PASSWORD 
      clear:
        POSTGRES_USER: postgres
    volumes:
      - "task_manager_db_data:/var/lib/postgresql/data"

